language: cpp
script: tests/test_uncrustify.sh
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install uncrustify
notifications:
  email:
    recipients: emil.maskovsky@xiriar.com
    on_success: change
    on_failure: always
