#!/bin/sh
#

# Copyright (c) 2013 Xiriar Software (http://www.xiriar.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

##
# @file
#
# Git pre-commit hook
#
# @author     Emil Maskovsky, emil.maskovsky@xiriar.com
# @date       2013/11/10
# @copyright  (c) 2013 Xiriar Software (http://www.xiriar.com/)
##


# Exit and fail on error immediately
set -e

# Execute the global pre-commit hook script
#
# Get the path from Git configuration "hooks.path" if set,
# use "$HOME/.gitconf/hooks" as a default.
exec "$(git config --path "hooks.path" || printf "$HOME/.gitconf/hooks")/pre-commit-all.sh"

# EOF
